spring:
  application:
    name: guessword-2
  liquibase:
    liquibase-schema: liquibase_schema
    change-log: classpath:db/changelog.xml

postgres.datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: postgres

mysql.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:32768/guessword
    username: root
    password: mysql

server:
  servlet:
    context-path: /api