spring:
  application:
    name: guessword-2
#  liquibase:
#    liquibase-schema: liquibase
#    change-log: classpath:db/changelog.xml
  jpa:
    hibernate:
      ddl-auto: validate

postgres.datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: vlenaf13

mysql.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/guessword
    username: alex
    password: vlenaf13

server:
  servlet:
    context-path: /api