spring:
  application:
    name: guessword-2
  liquibase:
    liquibase-schema: liquibase_schema
    change-log: classpath:db/changelog.xml

postgres.datasource:
    driver-class-name: org.postgresql.Driver
    jdbc-url: jdbc:postgresql://localhost:5432/guessword
    username: alex
    password: vlenaf13

mysql.datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: jdbc:mysql://localhost:3306/guessword
    username: alex
    password: vlenaf13

server:
  servlet:
    context-path: /api